# Required metadata
sonar.projectKey=pavelgrebenkov_python-project-50
sonar.organization=pavelgrebenkov
sonar.projectName=python-project-50
sonar.projectVersion=1.0.0

# Paths to scan
sonar.sources=gendiff
sonar.tests=tests

# Crucial exclusions (Do not scan millions of lines of dependency code)
sonar.exclusions=**/.venv/**,**/__pycache__/**,**/*.pyc

# Python specifics & Coverage maps
sonar.lnaguage=py
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
