""" Unit tests for the Json Formatter Module (formatter_json.py).

This module validates format_json(), which takes an internal representation (IR) difference tree,
generated by build_diff() of the Builder Module (diff_builder.py), and generates a JSON string
representing that IR. There are no line templates, path-tracking or indentation math — it's just
strightforward serialization.


The tests cover 12 cases - 6 for each type of IR, flat and nested. The tests cover the following possible situations:
1. empty dictionaries
2. unchanged status
3. added status
4. removed status
5. updated status
6. mixed (2. - 5.)
"""


import ast
import textwrap

from gendiff.formatters.formatter_json import format_json

from .helpers import _get_test_data_path, _read_test_file


# . FLAT IRs
# Case 1: flat => empty node
def test_format_json_flat_empty_node():
    # Arrange:
    node = []
    expected_output = "[]"

    # Act
    actual_output = format_json(node)

    # Assert
    assert actual_output == expected_output


# Case 2: flat => status: unchanged
def test_format_json_flat_status_unchanged():
    # Arrange:
    node = [{'key': 'host', 'status': 'unchanged', 'old_value': 'hexlet.io', 'new_value': 'hexlet.io', 'children': None}]

    expected_output = textwrap.dedent("""\
                                            [
                                              {
                                                "key": "host",
                                                "status": "unchanged",
                                                "old_value": "hexlet.io",
                                                "new_value": "hexlet.io",
                                                "children": null
                                              }
                                            ]""")

    # Act
    actual_output = format_json(node)

    # Assert
    assert actual_output == expected_output


# Case 3: flat => status: removed
def test_format_json_flat_status_removed():
    # Arrange:
    node = [{'key': 'host', 'status': 'removed', 'old_value': 'hexlet.io', 'new_value': None, 'children': None}]

    expected_output = textwrap.dedent("""\
                                            [
                                              {
                                                "key": "host",
                                                "status": "removed",
                                                "old_value": "hexlet.io",
                                                "new_value": null,
                                                "children": null
                                              }
                                            ]""")

    # Act
    actual_output = format_json(node)

    # Assert
    assert actual_output == expected_output


# Case 4: flat => status: added
def test_format_json_flat_status_added():
    # Arrange:
    node = [{'key': 'host', 'status': 'added', 'old_value': None, 'new_value': 'hexlet.io', 'children': None}]

    expected_output = textwrap.dedent("""\
                                            [
                                              {
                                                "key": "host",
                                                "status": "added",
                                                "old_value": null,
                                                "new_value": "hexlet.io",
                                                "children": null
                                              }
                                            ]""")

    # Act
    actual_output = format_json(node)

    # Assert
    assert actual_output == expected_output


# Case 5: flat => status: updated
def test_format_json_flat_status_updated():
    # Arrange:
    node = [{'key': 'host', 'status': 'updated', 'old_value': 'hexlet.io', 'new_value': 'hexlet.com', 'children': None}]

    expected_output = textwrap.dedent("""\
                                            [
                                              {
                                                "key": "host",
                                                "status": "updated",
                                                "old_value": "hexlet.io",
                                                "new_value": "hexlet.com",
                                                "children": null
                                              }
                                            ]""")

    # Act
    actual_output = format_json(node)

    # Assert
    assert actual_output == expected_output


# Case 6: flat => integrated
def test_format_json_flat_overall():
    # Arrange:
    node = ast.literal_eval(_read_test_file(_get_test_data_path("expected_ir_flat.txt")))
    expected_output = _read_test_file(_get_test_data_path("expected_json_flat.txt"))

    # Act
    actual_output = format_json(node)

    # Assert
    assert actual_output == expected_output


# II. NESTED IRs
# Case 1: nested => Empty node
def test_format_json_nest_empty_node():
    node = [
            {
                'key': 'common',
                'status': 'nested',
                'old_value': None,
                'new_value': None,
                'children': []
            }
        ]

    expected_output = textwrap.dedent("""\
                                            [
                                              {
                                                "key": "common",
                                                "status": "nested",
                                                "old_value": null,
                                                "new_value": null,
                                                "children": []
                                              }
                                            ]""")

    # Act
    actual_output = format_json(node)

    # Assert
    assert actual_output == expected_output


# Case 2: nested => status: unchanged
def test_format_json_nest_status_unchanged():
    # Arrange:
    node = [
            {
                'key': 'common',
                'status': 'nested',
                'old_value': None,
                'new_value': None,
                'children': [{'key': 'setting1', 'status': 'unchanged', 'old_value': 'Value 1', 'new_value': 'Value 1', 'children': None}]
            }
        ]

    expected_output = textwrap.dedent("""\
                                            [
                                              {
                                                "key": "common",
                                                "status": "nested",
                                                "old_value": null,
                                                "new_value": null,
                                                "children": [
                                                  {
                                                    "key": "setting1",
                                                    "status": "unchanged",
                                                    "old_value": "Value 1",
                                                    "new_value": "Value 1",
                                                    "children": null
                                                  }
                                                ]
                                              }
                                            ]""")

    # Act
    actual_output = format_json(node)

    # Assert
    assert actual_output == expected_output


# Case 3: nested => status: removed
def test_format_json_nest_status_removed():
    # Arrange:
    node = [
            {
                'key': 'common',
                'status': 'nested',
                'old_value': None,
                'new_value': None,
                'children': [{'key': 'setting1', 'status': 'removed', 'old_value': 'Value 1', 'new_value': None, 'children': None}]
            }
        ]

    expected_output = textwrap.dedent("""\
                                            [
                                              {
                                                "key": "common",
                                                "status": "nested",
                                                "old_value": null,
                                                "new_value": null,
                                                "children": [
                                                  {
                                                    "key": "setting1",
                                                    "status": "removed",
                                                    "old_value": "Value 1",
                                                    "new_value": null,
                                                    "children": null
                                                  }
                                                ]
                                              }
                                            ]""")

    # Act
    actual_output = format_json(node)

    # Assert
    assert actual_output == expected_output


# Case 4: nest => status: added
def test_format_json_nest_status_added():
    # Arrange:
    node = [
            {
                'key': 'common',
                'status': 'nested',
                'old_value': None,
                'new_value': None,
                'children': [{'key': 'setting1', 'status': 'added', 'old_value': None, 'new_value': 'Value 1', 'children': None}]
            }
        ]

    expected_output = textwrap.dedent("""\
                                            [
                                              {
                                                "key": "common",
                                                "status": "nested",
                                                "old_value": null,
                                                "new_value": null,
                                                "children": [
                                                  {
                                                    "key": "setting1",
                                                    "status": "added",
                                                    "old_value": null,
                                                    "new_value": "Value 1",
                                                    "children": null
                                                  }
                                                ]
                                              }
                                            ]""") 

    # Act
    actual_output = format_json(node)

    # Assert
    assert actual_output == expected_output


# Case 5: nest => status: updated
def test_format_json_nest_status_updated():
    # Arrange:
    node = [
            {
                'key': 'common',
                'status': 'nested',
                'old_value': None,
                'new_value': None,
                'children': [{'key': 'setting1', 'status': 'updated', 'old_value': 'Value 1', 'new_value': 'Value 2', 'children': None}]
            }
        ]

    expected_output = textwrap.dedent("""\
                                            [
                                              {
                                                "key": "common",
                                                "status": "nested",
                                                "old_value": null,
                                                "new_value": null,
                                                "children": [
                                                  {
                                                    "key": "setting1",
                                                    "status": "updated",
                                                    "old_value": "Value 1",
                                                    "new_value": "Value 2",
                                                    "children": null
                                                  }
                                                ]
                                              }
                                            ]""")

    # Act
    actual_output = format_json(node)

    # Assert
    assert actual_output == expected_output


# Case 6: nest => Integrated
def test_format_json_nest_overall():
    # Arrange:
    node = ast.literal_eval(_read_test_file(_get_test_data_path("expected_ir_nest.txt")))
    expected_output = _read_test_file(_get_test_data_path("expected_json_nest.txt"))

    # Act
    actual_output = format_json(node)

    # Assert
    assert actual_output == expected_output
