""" Unit tests for the Plain Formatter Module (formatter_plain.py).

This module validates format_plain(), which takes an internal representation (IR) difference tree,
generated by build_diff() of the Builder Module (diff_builder.py), and generates a custom string, 'plain'.

Node formatting rules:
added	   Property '{path}' was added with value: {formatted_value}
removed	   Property '{path}' was removed
updated	   Property '{path}' was updated. From {old_formatted_value} to {new_formatted_value}
unchanged  Not shown

Value formatting rules:
Strings => wrapped in single quotes: 'blah blah' or '' if empty string
Numbers (int, float) => no quotes: 42, 3.14
Booleans => JSON notation: true, false
None => null
Composite values (dict or list) => the literal string [complex value]

The tests cover 12 cases - 6 for each type of IR, flat and nested. The tests cover the following possible situations:
1. empty dictionaries
2. unchanged status
3. added status
4. removed status
5. updated status
6. mixed (2. - 5.)
"""

import ast

from gendiff.formatters.formatter_plain import format_plain

from .helpers import _get_test_data_path, _read_test_file


# FLAT IRs
# Case 1: flat => empty node
def test_format_plain_flat_empty_node() -> None:
    # Arrange:
    node = []
    expected_output = ""

    # Act
    actual_output = format_plain(node)

    # Assert
    assert actual_output == expected_output


# Case 2: flat => status: unchanged
def test_format_plain_flat_status_unchanged() -> None:
    # Arrange:
    node = [{'key': 'host', 'status': 'unchanged', 'old_value': 'hexlet.io', 'new_value': 'hexlet.io', 'children': None}]
    expected_output = ""

    # Act
    actual_output = format_plain(node)

    # Assert
    assert actual_output == expected_output


# Case 3: flat => status: removed
def test_format_plain_flat_status_removed() -> None:
    # Arrange:
    node = [{'key': 'host', 'status': 'removed', 'old_value': 'hexlet.io', 'new_value': None, 'children': None}]
    expected_output = "Property 'host' was removed"

    # Act
    actual_output = format_plain(node)

    # Assert
    assert actual_output == expected_output


# Case 4: flat => status added
def test_format_plain_flat_status_added() -> None:
    # Arrange:
    node = [{'key': 'host', 'status': 'added', 'old_value': None, 'new_value': 'hexlet.io', 'children': None}]
    expected_output = "Property 'host' was added with value: 'hexlet.io'"

    # Act
    actual_output = format_plain(node)

    # Assert
    assert actual_output == expected_output


# Case 5: flat => updated node
def test_format_plain_flat_status_updated() -> None:
    # Arrange:
    node = [{'key': 'host', 'status': 'updated', 'old_value': 'hexlet.io', 'new_value': 'hexlet.com', 'children': None}]
    expected_output = "Property 'host' was updated. From 'hexlet.io' to 'hexlet.com'"

    # Act
    actual_output = format_plain(node)

    # Assert
    assert actual_output == expected_output


# Case 6: flat => integrated
def test_format_plain_flat_overall() -> None:
    # Arrange:
    node = ast.literal_eval(_read_test_file(_get_test_data_path("expected_ir_flat.txt")))
    expected_output = _read_test_file(_get_test_data_path("expected_plain_flat.txt"))
    # Act
    actual_output = format_plain(node)
    print(actual_output)

    # Assert
    assert actual_output == expected_output


# II. NESTED IRs
# Case 1: nested => Empty node
def test_format_plain_nest_empty_node() -> None:
    node = [
            {
                'key': 'common',
                'status': 'nested',
                'old_value': None,
                'new_value': None,
                'children': []
            }
        ]

    expected_output = ""

    # Act
    actual_output = format_plain(node)

    # Assert
    assert actual_output == expected_output


# Case 2: nested => status: unchanged
def test_format_plain_nest_status_unchanged() -> None:
    # Arrange:
    node = [
            {
                'key': 'common',
                'status': 'nested',
                'old_value': None,
                'new_value': None,
                'children': [{'key': 'setting1', 'status': 'unchanged', 'old_value': 'Value 1', 'new_value': 'Value 1', 'children': None}]
            }
        ]
    expected_output = ""

    # Act
    actual_output = format_plain(node)

    # Assert
    assert actual_output == expected_output


# Case 3: nested => status: removed
def test_format_plain_nest_status_removed() -> None:
    # Arrange:
    node = [
            {
                'key': 'common',
                'status': 'nested',
                'old_value': None,
                'new_value': None,
                'children': [{'key': 'setting1', 'status': 'removed', 'old_value': 'Value 1', 'new_value': None, 'children': None}]
            }
        ]
    expected_output = "Property 'common.setting1' was removed"

    # Act
    actual_output = format_plain(node)

    # Assert
    assert actual_output == expected_output


# Case 4: nest => Added node
def test_format_plain_nest_status_added() -> None:
    # Arrange:
    node = [
            {
                'key': 'common',
                'status': 'nested',
                'old_value': None,
                'new_value': None,
                'children': [{'key': 'setting1', 'status': 'added', 'old_value': None, 'new_value': 'Value 1', 'children': None}]
            }
        ]
    expected_output = "Property 'common.setting1' was added with value: 'Value 1'"

    # Act
    actual_output = format_plain(node)

    # Assert
    assert actual_output == expected_output


# Case 5: nest => Updated node
def test_format_plain_nest_status_updated() -> None:
    # Arrange:
    node = [
            {
                'key': 'common',
                'status': 'nested',
                'old_value': None,
                'new_value': None,
                'children': [{'key': 'setting1', 'status': 'updated', 'old_value': 'Value 1', 'new_value': 'Value 2', 'children': None}]
            }
        ]
    expected_output = "Property 'common.setting1' was updated. From 'Value 1' to 'Value 2'"

    # Act
    actual_output = format_plain(node)

    # Assert
    assert actual_output == expected_output


# Case 6: nest => Integrated
def test_format_plain_nest_overall() -> None:
    # Arrange:
    node = ast.literal_eval(_read_test_file(_get_test_data_path("expected_ir_nest.txt")))
    expected_output = _read_test_file(_get_test_data_path("expected_plain_nest.txt"))

    # Act
    actual_output = format_plain(node)

    # Assert
    assert actual_output == expected_output
