""" Unit tests for the Stylish Formatter Module (formatter_stylish.py).

This module validates format_stylish(), which takes an internal representation (RI) difference tree,
generated by build_diff() of the Builder Module (diff_builder.py), and generates a custom string, 'stylish',
according to the follwing rules:

- Each level of nesting adds 4 spaces - i.e. depth * 4 spaces;
- If there are prefixes, offeset the indentation by 2 spaces + prefix + space (total: 4 spaces), then the key and value;
- For each node, the line starts with either - (removed), + (added), or (unchanged/nested header);
- For unchanged primitive values: key: value (4 spaces).
- For added/removed primitive values: + key: value or - key: value (2 spaces, sign, space).
- For updated primitive values: two lines - first removed, followed by added - with the top-level output starting with { on its own line and ends with } on its own line;
- For 'nested' nodes, the line is key: { (with 4 spaces, no sign), then the children are indented further, and the closing } is on its own line with the same indentation as the opening line;
- EXAMPLE:
  {
      common: {
                + follow: false
                  setting1: Value 1
                - setting2: 200
                ...
     }
  }

The tests cover 12 cases - 6 for each type of IR, flat and nested. The tests cover the following possible situations:
1. empty dictionaries
2. unchanged status
3. added status
4. removed status
5. updated status
6. mixed (2. - 5.)
"""

from gendiff.formatters.formatter_stylish import format_stylish
from pathlib import Path
from .helpers import _get_test_data_path, _read_test_file
import pytest
import ast


#. FLAT IRs
# Case 1: flat => empty node
def test_format_stylish_flat_empty_node():
    # Arrange:
    node = []
    expected_output = ""

    # Act
    actual_output = format_stylish(node)

    # Assert
    assert actual_output == expected_output


# Case 2: flat => status: unchanged
def test_format_stylish_flat_status_unchanged():
    # Arrange:
    node = [{'key': 'host', 'status': 'unchanged', 'old_value': 'hexlet.io', 'new_value': 'hexlet.io', 'children': None}]

    expected_output = (
                        "{\n"
                        "    host: hexlet.io\n"
                        "}"
                    )


    # Act
    actual_output = format_stylish(node)

    # Assert
    assert actual_output == expected_output


# Case 3: flat => status: removed
def test_format_stylish_flat_status_removed():
    # Arrange:
    node = [{'key': 'host', 'status': 'removed', 'old_value': 'hexlet.io', 'new_value': None, 'children': None}]
    expected_output = (
                        "{\n"
                        "  - host: hexlet.io\n"
                        "}"
                    )


    # Act
    actual_output = format_stylish(node)

    # Assert
    assert actual_output == expected_output


# Case 4: flat => status added
def test_format_stylish_flat_status_added():
    # Arrange:
    node = [{'key': 'host', 'status': 'added', 'old_value': None, 'new_value': 'hexlet.io', 'children': None}]
    expected_output = (
                        "{\n"
                        "  + host: hexlet.io\n"
                        "}"
                    )


    # Act
    actual_output = format_stylish(node)

    # Assert
    assert actual_output == expected_output


# Case 5: flat => updated node
def test_format_stylish_flat_status_updated():
    # Arrange:
    node = [{'key': 'host', 'status': 'updated', 'old_value': 'hexlet.io', 'new_value': 'hexlet.com', 'children': None}]
    expected_output = (
                        "{\n"
                        "  - host: hexlet.io\n"
                        "  + host: hexlet.com\n"
                        "}"
                    )


    # Act
    actual_output = format_stylish(node)

    # Assert
    assert actual_output == expected_output


# Case 6: flat => integrated
def test_format_stylish_flat_overall():
    # Arrange:
    node = ast.literal_eval(_read_test_file(_get_test_data_path("expected_ir_flat.txt")))
    expected_output = _read_test_file(_get_test_data_path("expected_stylish_flat.txt"))


    # Act
    actual_output = format_stylish(node)

    # Assert
    assert actual_output == expected_output


# II. NESTED IRs
# Case 1: nested => Empty node
def test_format_stylish_nest_empty_node():
    # Arrange:
    node = [
            {
                'key': 'common',
                'status': 'nested',
                'old_value': None,
                'new_value': None,
                'children': []
            }
        ]

    expected_output = (
                        "{\n"
                        "    common: \n"
                        "}"

                    )

    # Act
    actual_output = format_stylish(node)

    # Assert
    assert actual_output == expected_output


# Case 2: nested => status: unchanged
def test_format_stylish_nest_status_unchanged():
    # Arrange:
    node = [
            {
                'key': 'common',
                'status': 'nested',
                'old_value': None,
                'new_value': None,
                'children': [{'key': 'setting1', 'status': 'unchanged', 'old_value': 'Value 1', 'new_value': 'Value 1', 'children': None}]
            }
        ]

    expected_output = (
                        "{\n"
                        "    common: {\n"
                        "        setting1: Value 1\n"
                        "    }\n"
                        "}"
                    )


    # Act
    actual_output = format_stylish(node)

    # Assert
    assert actual_output == expected_output


# Case 3: nested => status: removed
def test_format_stylish_nest_status_removed():
    # Arrange:
    node = [
            {
                'key': 'common',
                'status': 'nested',
                'old_value': None,
                'new_value': None,
                'children': [{'key': 'setting1', 'status': 'removed', 'old_value': 'Value 1', 'new_value': None, 'children': None}]
            }
        ]

    expected_output = (
                        "{\n"
                        "    common: {\n"
                        "      - setting1: Value 1\n"
                        "    }\n"
                        "}"
                    )


    # Act
    actual_output = format_stylish(node)

    # Assert
    assert actual_output == expected_output


# Case 4: nest => Added node
def test_format_stylish_nest_status_added():
    # Arrange:
    node = [
            {
                'key': 'common',
                'status': 'nested',
                'old_value': None,
                'new_value': None,
                'children': [{'key': 'setting1', 'status': 'added', 'old_value': None, 'new_value': 'Value 1', 'children': None}]
            }
        ]

    expected_output = (
                        "{\n"
                        "    common: {\n"
                        "      + setting1: Value 1\n"
                        "    }\n"
                        "}"
                    )


    # Act
    actual_output = format_stylish(node)

    # Assert
    assert actual_output == expected_output


# Case 5: nest => Updated node
def test_format_stylish_nest_status_updated():
    # Arrange:
    node = [
            {
                'key': 'common',
                'status': 'nested',
                'old_value': None,
                'new_value': None,
                'children': [{'key': 'setting1', 'status': 'updated', 'old_value': 'Value 1', 'new_value': 'Value 2', 'children': None}]
            }
        ]

    expected_output = (
                        "{\n"
                        "    common: {\n"
                        "      - setting1: Value 1\n"
                        "      + setting1: Value 2\n"
                        "    }\n"
                        "}"
                    )


    # Act
    actual_output = format_stylish(node)

    # Assert
    assert actual_output == expected_output


# Case 6: nest => Integrated
def test_format_stylish_nest_overall():
    # Arrange:
    node = ast.literal_eval(_read_test_file(_get_test_data_path("expected_ir_nest.txt")))
    expected_output = _read_test_file(_get_test_data_path("expected_stylish_nest.txt"))


    # Act
    actual_output = format_stylish(node)

    # Assert
    assert actual_output == expected_output
