""" Json Formatter Module (formatter_json.py) for building JSON strings.

This module contains the function format_json() that takes an internal representation (IR) difference tree,
generated by build_diff() of the Builder Module (diff_builder.py), and generates a JSON string representing that IR.
There are no line templates, path-tracking or  indentation math — it's just straightforward serialization.
"""

import json


def format_json(diff_tree_node: list) -> str:
	"""
        Read an IR, depending on the value of the key "status", determine its structure
        and return a tree-like output.

        Args:
                diff_tree_node (list): Each node is a dictionary with the following possible key-value pairs:
                - key: the name of the key.
                - status: 'added', / 'removed', / 'updated', / 'unchanged', / 'nested'.
                - old_value (optional): the value from the first file (for 'removed', 'updated').
                - new_value (optional): the value from the second file (for 'added', 'updated').
                - children (optional): a list of child nodes, only for 'nested' status.

        Returns:
                JSON string (str): a serialized representation of IR.
        """
	json_string = json.dumps(diff_tree_node, indent=2)

	return json_string
