""" Stylish Formatter Module (formatter_stylish.py) for building a custom string, stylish.

This module contains the function format_stylish() that takes an internal representation (RI) difference tree,
generated by build_diff() of the Builder Module (diff_builder.py), and generates a custom string, 'stylish'

It also contains the helper function _format_value().
"""

from typing import Any


def _format_value(value: Any, replacer: str, spaces_count: int, level: int) -> Any:
	"""
	1) If the input value is a non-empty Python  dictionary, unpack it;
	2) If the input Python value is primitive, determine its type and convert to a strings.

        Args:
                value: Any Python data type object;
		replacer: A string denoting an indent character (e.g. space, -, * ... etc);
		spaces_count: An integer donoting the number of spaces the indent consists of;
		level: An integer denoting the level of nesting, if a dictionary is nested.
        Returns:
                string: All input values are converted to strings.
		Nested dictionary: If the value is a nested dictionary, it's unpacked and formatted
		with appropriate indents and / or prefixes
        """
	# ------ Dictionaries --------------
	if isinstance(value, dict) and value != {}:
		result = "{\n"

		for k, v in value.items():
			next_level = level + 1
			open_indent = replacer * (spaces_count * next_level)

			result += f"{open_indent}{k}: {_format_value(v, replacer, spaces_count, next_level)}\n"

		close_indent = replacer * (spaces_count * level)
		return f"{result}{close_indent}}}"

	# ------ Primitive values ------------------
	else:
		match value:
			case bool():
				return str(value).lower()
			case int():
				return str(value)
			case float():
				return str(value)
			case None:
				return "null"
			case _:
				return str(value)


def format_stylish(diff_tree_node: list, replacer: str = ' ', spaces_count: int = 4, level: int = 1) -> str:
	"""
	Read an IR, depending on the value of the key "status", determine its structure
	and return a tree-like output.

        Args:
                diff_tree_node (list): Each node is a dictionary with the following possible key-value pairs:
		- key: the name of the key.
		- status: 'added', / 'removed', / 'updated', / 'unchanged', / 'nested'.
		- old_value (optional): the value from the first file (for 'removed', 'updated').
		- new_value (optional): the value from the second file (for 'added', 'updated').
		- children (optional): a list of child nodes, only for 'nested' status.

        Returns:
                tree-like output (str): Changes are indicated with - (removed), + (added), and "  " (unchanged).
	"""

	# IR is an empty list
	if diff_tree_node == []:
		return ""

	# Create indents
	full_indent = replacer * (spaces_count * level)
	offset_indent = replacer * ((spaces_count * level) - 2)
	close_indent = replacer * (spaces_count * (level - 1))

	output_str = "{\n"

	# Extract nodes
	for node in diff_tree_node:
		status = node['status']
		if status == "unchanged":
			output_str += f"{full_indent}{node['key']}: {_format_value(node['old_value'], None, None, None)}\n"
		elif status == "removed":
			output_str += f"{offset_indent}- {node['key']}: {_format_value(node['old_value'], replacer, spaces_count, level)}\n"
		elif status == "added":
			output_str += f"{offset_indent}+ {node['key']}: {_format_value(node['new_value'], replacer, spaces_count, level)}\n"
		elif status == "updated":
			output_str += (f"{offset_indent}- {node['key']}: {_format_value(node['old_value'], replacer, spaces_count, level)}\n"
				f"{offset_indent}+ {node['key']}: {_format_value(node['new_value'], replacer, spaces_count, level)}\n")
		elif status == "nested":
			# Recursively process the value, if status is nested.
			output_str += (f"{full_indent}{node['key']}: {format_stylish(node['children'], replacer, spaces_count, level + 1)}\n")
	output_str += f"{close_indent}}}"

	return output_str
