""" Plain Formatter Module (formatter_plain.py) for building a custom string, 'plain'.

This module contains the function format_plain() that takes an internal representation (IR) difference tree,
generated by build_diff() of the Builder Module (diff_builder.py), and generates a custom string, 'plain'.

It also contains the helper function _format_plain_value(), which converts Python objects into strings
according to the following rules:

Strings => wrapped in single quotes: 'blah blah' or '' if  empty string
Numbers (int, float) => no quotes: 42, 3.14
Booleans => JSON notation: true, false
None => null
Composite values (dict or list) => the literal string [complex value]
"""


from typing import Any


def _format_plain_value(value: Any) -> str:
	"""
	Determine the data type of the input value and convert it to a string.

	Args:
		value: any Python data type object.

	Returns:
		string: All input values are converted to strings.
	"""
	match value:
		case bool():
			return str(value).lower()
		case int():
			return str(value)
		case float():
			return str(value)
		case None:
			return "null"
		case str():
			return repr(value)
		case dict():
			return "[complex value]"
		case list():
			return "[complex value]"
		case _:
			return str(value)


def format_plain(diff_tree_node: list, path=None) -> str:
	"""
	Read an IR, depending on the value of the key "status", determine its structure
	and return a flat list of sentences, each describing one changed property.

	Args:
		diff_tree_node (list): Each node is a dictionary with the following possible key-value pairs:
		key: the name of the key.
		status: 'added', / 'removed', / 'updated', / 'unchanged', / 'nested'.
		old_value (optional): the value from the first file (for 'removed', 'updated').
		new_value (optional): the value from the second file (for 'added', 'updated').
		children (optional): a list of child nodes, only for 'nested' status.

	Returns:
		a flat, newline-separated string of sentences (str): each sentence describes a single changed property.
	"""

	if path is None:
		path = []

	if diff_tree_node == []:
		return ""

	path_lines = []

	for node in diff_tree_node:
		status = node['status']
		# Add the current node's label to a new path
		current_path = path + [node["key"]]
		if status == "unchanged":
			continue
		elif status == "removed":
			path_lines.append(f"Property '{'.'.join(current_path)}' was removed")
		elif status == "added":
			path_lines.append(f"Property '{'.'.join(current_path)}' was added with value: {_format_plain_value(node['new_value'])}")
		elif status == "updated":
			path_lines.append(
				f"Property '{'.'.join(current_path)}' was updated. "
				f"From {_format_plain_value(node['old_value'])} "
				f"to {_format_plain_value(node['new_value'])}"
			)
		elif status == "nested":
			# Recursively process the value, if status is nested.
			result = format_plain(node["children"], current_path)
			if result:
				path_lines.append(result)
	final_path = "\n".join(path_lines)

	return final_path
