name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       # Pull down the repository source code securly using v6
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Important for Git blame history in SonarQube
       # Spin up the target Python environment using v7
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"
        # Use uv for managing dependencies
      - name: Install dependencies
        run: |
          pip install uv
          make install
        # ruff check
      - name: Run linter
        run: |
          make lint
        # pytest check
      - name: Run pytest
        run: |
          make test
        # pytest test coverage
      - name: Run pytest test coverage
        run: |
          make test-coverage
        # SonarQube scanner using v8
      - name: Run SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v8
        with:
          skipSignatureVerification: true
          args: >
            -X
            -Dsonar.verbose=${{ runner.debug == '1' && 'true' || 'false' }}"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
