name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       # Pull down the repository source code securly using v6
      - name: Checkout Code
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Important for Git blame history in SonarQube
       # Spin up the target Python environment using v6
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12 - 3.14"
        # Use uv for managing dependencies
      - name: Install dependencies
        run: |
          pip install uv
          make install
        # ruff check
      - name: Run linter
        run: |
          make lint
        # pytest check
      - name: Run pytest
        run: |
          make test
        # pytest test coverage
      - name: Run pytest test coverage
        run: |
          make test-coverage
        # SonarQube scanner
      - name: Run SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secretes.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=hexlet-boilerplates_python-package
            -Dsonar.organization=hexlet-boilerplates
            -Dsonar.python.coverage.reportPaths=coverage.xml
